public class CodonTranslater {
    public static String codon2aa(String codon) {
        switch (codon) {
            case "GCA":
                return "A";
            case "GCC":
                return "A";
            case "GCG":
                return "A";
            case "GCU":
                return "A";
            case "UGC":
                return "C";
            case "UGU":
                return "C";
            case "GAC":
                return "D";
            case "GAU":
                return "D";
            case "GAA":
                return "E";
            case "GAG":
                return "E";
            case "UUC":
                return "F";
            case "UUU":
                return "F";
            case "GGA":
                return "G";
            case "GGC":
                return "G";
            case "GGG":
                return "G";
            case "GGU":
                return "G";
            case "CAC":
                return "H";
            case "CAU":
                return "H";
            case "AUA":
                return "I";
            case "AUC":
                return "I";
            case "AUU":
                return "I";
            case "AAA":
                return "K";
            case "AAG":
                return "K";
            case "CUA":
                return "L";
            case "CUC":
                return "L";
            case "CUG":
                return "L";
            case "CUU":
                return "L";
            case "UUA":
                return "L";
            case "UUG":
                return "L";
            case "AUG":
                return "M";
            case "AAC":
                return "N";
            case "AAU":
                return "N";
            case "CCA":
                return "P";
            case "CCC":
                return "P";
            case "CCG":
                return "P";
            case "CCU":
                return "P";
            case "CAA":
                return "Q";
            case "CAG":
                return "Q";
            case "AGA":
                return "R";
            case "AGG":
                return "R";
            case "CGA":
                return "R";
            case "CGC":
                return "R";
            case "CGG":
                return "R";
            case "CGU":
                return "R";
            case "AGC":
                return "S";
            case "AGU":
                return "S";
            case "UCA":
                return "S";
            case "UCC":
                return "S";
            case "UCG":
                return "S";
            case "UCU":
                return "S";
            case "ACA":
                return "U";
            case "ACC":
                return "U";
            case "ACG":
                return "U";
            case "ACU":
                return "U";
            case "GUA":
                return "V";
            case "GUC":
                return "V";
            case "GUG":
                return "V";
            case "GUU":
                return "V";
            case "UGG":
                return "W";
            case "UAC":
                return "Y";
            case "UAU":
                return "Y";
            case "UGA":
                return "*";
            case "UAA":
                return "*";
            case "UAG":
                return "*";
            default:
                return "-1";
        }
    }
}
